### ISSUE TITLE
Is there a way to automatically add new typed tags to the array? Or to highlight them at least?

### ISSUE THREAD

**Issue by apbln** [syropian/vue-tribute#16]

**Comment by syropian** [comment]
This isn't a core function of the parent library (and by association, this wrapper). 

Because this is a simple Vue wrapper around another library, I encourage you to read the official [tribute documentation](https://github.com/zurb/tribute) thoroughly, and file any feature requests there. Issues should only be created here if there's a bug with the Vue-specific integration. 

Thanks!
