### ISSUE TITLE
super duper issue found dude!!

### ISSUE THREAD

**Issue by hd-diegocortez** [syropian/vue-tribute#23]
Of course I'm not going to use this wrapper.
Sorry have hurt your feelings bro, maybe something is not going well in life, understandable.
Btw, I thought you were a busy person ha

**Comment by syropian** [comment]
Sorry friend, I don't owe you anything. You're rude, abrasive, and I doubt anyone would be willing to help you due to your angsty, entitled attitude. 

> maybe something is not going well in life

My life is great thanks, I work a well-paying full-time job, and have a beautiful family. What makes me life bad is dealing with childish people like you.

Congrats, you've earned yourself a block. Have a great day!
